### ISSUE TITLE
Can not import cv2

### ISSUE THREAD

**Issue by hardcookies** [jrobchin/Computer-Vision-Basics-with-Python-Keras-and-OpenCV#1]
Hi, I installed the packages as README.md. But when I import cv2, there is a error.
```
import cv2

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-c8ec22b3e787> in <module>()
----> 1 import cv2

ImportError: dlopen(/Users/james/anaconda3/envs/cv/lib/python3.5/site-packages/cv2.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libfreetype.6.dylib
  Referenced from: /Users/james/anaconda3/envs/cv/lib/libopencv_freetype.3.4.dylib
  Reason: Incompatible library version: libopencv_freetype.3.4.dylib requires version 22.0.0 or later, but libfreetype.6.dylib provides version 21.0.0
````
What should I do?

**Comment by jrobchin** [comment]
I would check these issues to start: https://github.com/conda-forge/opencv-feedstock/issues/69 and https://github.com/ContinuumIO/anaconda-issues/issues/1266.

I have never seen this specific error but from reading those issues, some possible troubleshooting steps could be:
1. `conda install openblas=0.2.19` [See here.](https://github.com/conda-forge/opencv-feedstock/issues/69#issuecomment-329232700)
2. Create a new env and install only OpenCV:
`conda install -c conda-forge opencv --override-channels`
[See here](https://github.com/conda-forge/opencv-feedstock/issues/69#issuecomment-303048472)
3. Uninstall OpenCV and install the _Menpo_ version (Seems to work for a lot of people, just not 100% sure if all features are identical):
`conda uninstall opencv`
`conda install -c https://conda.binstar.org/menpo opencv`
[See here.](https://github.com/ContinuumIO/anaconda-issues/issues/1266#issuecomment-368108833)

It'd also help if you posted your `conda list` and `conda info`.

**Comment by hardcookies** [comment]
Thank you! I have solved this problem by
```
conda install -c https://conda.anaconda.org/menpo opencv3
```

**Comment by jrobchin** [comment]
Great! I'll add that to the readme.
