### ISSUE TITLE
Typo error `CURR_POS` and undefined function `get_unique_name`.

### ISSUE THREAD

**Issue by ZhengPeng7** [jrobchin/Computer-Vision-Basics-with-Python-Keras-and-OpenCV#3]
Hi, Jason Chin:
In the third last cell in the notebook, there are `CURR_POS`, which might should be `CURR_POSE`;
And function `get_unique_name` appears twice, but I'm confused where it is from.
Thanks for your reply in advance:)

**Comment by jrobchin** [comment]
Hi Zheng Peng,

You're absolutely right. 

In response to the CURR_POS/CURR_POSE: in the completed demo cell that you mentioned, the entire if statement (when 's' is pressed) should be **removed**. That was a copy-paste error when I was putting together the final demo cell and is only meant to be in the data collection cells. 

In response to the get_unique_name(), I'm not sure why it's not implemented in the notebook, but it's meant to parse the target folder for the pose training image and increment the image number (although it could just use a static variable to keep track of the number of images captured).

Feel free to submit pull requests to fix these two issues, if not I will fix it ASAP.

I'll leave the issue open until it's fixed.

Thanks for checking out the notebook, let me know what you think!
