### ISSUE TITLE
Access to training data

### ISSUE THREAD

**Issue by kfkonrad** [jrobchin/Computer-Vision-Basics-with-Python-Keras-and-OpenCV#6]
I'm working on a project based on your model for gesture recognition and I'm wondering whether you could give me access to your training data. The repository includes only [a few examples](https://github.com/jrobchin/Computer-Vision-Basics-with-Python-Keras-and-OpenCV/tree/master/images/preview).

That'd be great help for tweaking your model for my needs, many thanks in advance.

**Comment by jrobchin** [comment]
You're supposed to create the training data on your own as part of the tutorial.
